### ISSUE TITLE
I think it dont work for project which have set AUTH_USER_MODEL = 'accounts.User'?

### ISSUE THREAD

**Issue by akshaymishra5395** [Narsil/django-userpreferences#6]
i tried this in my project ,and i am gettting no module name Fields

```
home/akshay/thirdwave/ThirdWave/ThirdWave/settings/base.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[0](_exception[1]).with_traceback(_exception[2])
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/preferences/models.py", line 4, in <module>
    import fields
ModuleNotFoundError: No module named 'fields'

Traceback (most recent call last):
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/apps/registry.py", line 155, in get_app_config
    return self.app_configs[app_label]
KeyError: 'accounts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 165, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL, require_ready=False)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/apps/registry.py", line 205, in get_model
    app_config = self.get_app_config(app_label)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/apps/registry.py", line 162, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'accounts'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 95, in handle
    self.run(**options)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 102, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 579, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 564, in start_django
    reloader.run(django_main_thread)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 272, in run
    get_resolver().urlconf_module
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/urls/resolvers.py", line 564, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/akshay/thirdwave/ThirdWave/ThirdWave/urls.py", line 21, in <module>
    from accounts.views import login_return,login_user,logout_user
  File "/home/akshay/thirdwave/ThirdWave/accounts/views.py", line 15, in <module>
    from rest_framework_simplejwt import views as jwt_views
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/rest_framework_simplejwt/views.py", line 4, in <module>
    from . import serializers
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/rest_framework_simplejwt/serializers.py", line 6, in <module>
    from .state import User
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/rest_framework_simplejwt/state.py", line 6, in <module>
    User = get_user_model()
  File "/home/akshay/thirdwave/ThirdWave/venv/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 170, in get_user_model
    "AUTH_USER_MODEL refers to model '%s' that has not been installed" % settings.AUTH_USER_MODEL
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'accounts.User' that has not been installed
```

**Comment by Narsil** [comment]
This projet was created 9 years ago, you probably need to rewrite it to be able to use it with modern Django.

Sorry about this.
